#!/usr/bin/env perl
use strict;
use warnings;

our $VERSION = '0.001001';

use App::Yath::Util qw/load_command/;

my $cmd_name;
if (@ARGV && -f $ARGV[0] && $ARGV[0] =~ m/\.jsonl(\.bz2|\.gz)$/) {
    $cmd_name = 'replay';
}
elsif(!@ARGV || -d $ARGV[0] || -f $ARGV[0] || substr($ARGV[0],0,1) eq '-') {
    $cmd_name = 'test';
}
else {
    $cmd_name = shift @ARGV;
}

my $cmd_class = load_command($cmd_name);

my $cmd = $cmd_class->new(args => \@ARGV);
exit $cmd->run;
