#!/usr/bin/env perl
use strict;
use warnings;

use App::Yath::Util qw/load_command/;

my $cmd_name;
if (@ARGV && $ARGV[0] =~ m/^--?h(elp)?$/) {
    shift @ARGV;
    $cmd_name = 'help';
}
elsif(!@ARGV || -d $ARGV[0] || -f $ARGV[0] || substr($ARGV[0],0,1) eq '-') {
    $cmd_name = 'test';
}
else {
    $cmd_name = shift @ARGV;
}

my $cmd_class = load_command($cmd_name);

my $cmd = $cmd_class->new(args => \@ARGV);
exit $cmd->run;
